// Generated by CoffeeScript 1.7.1
var americano, port;

americano = require('americano');

port = process.env.PORT || 31436;

americano.start({
  name: 'Zero-Feeds',
  port: port
}, function(err, app, server) {
  return require("./server/models/zfparam").removeOldParams();
});
