// Generated by CoffeeScript 1.10.0
var americano, port;

americano = require('americano');

port = process.env.PORT || 31436;

americano.start({
  name: 'Zero-Feeds',
  port: port
}, function(err, app, server) {
  var Feed;
  require("./server/models/zfparam").removeOldParams();
  Feed = americano.getModel('Feed', {
    'title': {
      type: String
    },
    'url': {
      type: String
    },
    'last': {
      type: String
    },
    'tags': {
      type: JSON
    },
    'description': {
      type: String
    },
    'content': {
      type: String
    },
    'created': {
      type: Date,
      "default": Date
    },
    'updated': {
      type: Date,
      "default": Date
    }
  });
  return Feed.request("byTags", function(err, feeds) {
    var feed, i, len, results, tags;
    results = [];
    for (i = 0, len = feeds.length; i < len; i++) {
      feed = feeds[i];
      if (typeof feed.tags === "string") {
        tags = feed.tags.split(",");
        feed.tags = tags;
        results.push(feed.save());
      } else {
        results.push(void 0);
      }
    }
    return results;
  });
});
