// Generated by CoffeeScript 1.10.0
var americano;

americano = require('americano-cozy');

module.exports = {
  feed: {
    byTags: function(doc) {
      return emit(doc.tags, doc);
    }
  },
  zfparam: {
    byName: function(doc) {
      return emit(doc.name, doc);
    }
  }
};
