// Generated by CoffeeScript 1.9.3
(function() {
  var Param, americano, http;

  americano = require('americano-cozy');

  http = require('http');

  module.exports = Param = americano.getModel('ZFParam', {
    'paramId': {
      type: String
    },
    'name': {
      type: String
    },
    'value': {
      type: String
    }
  });

  Param.removeOldParams = function() {
    var OldParam;
    OldParam = americano.getModel('Param', {
      'paramId': {
        type: String
      }
    });
    return OldParam.request("byName", function(err, found) {
      if (found) {
        if (found.length === 2) {
          if (found[0].paramId === "cozy-bookmarks-name") {
            if (found[1].paramId === "show-new-links") {
              return OldParam.destroyAll(function() {
                return console.log("Old parameters have been destroyed");
              });
            }
          }
        }
      }
    });
  };

  Param.all = function(params, callback) {
    return Param.request("byName", params, callback);
  };

  Param.prototype.update = function(params, callback) {
    var param;
    param = this;
    param.save();
    return callback.call(param);
  };

}).call(this);
